mozilla/glean.js

.circleci/config.yml, bin/build-size-check.sh, bin/qt-js-check.sh, samples/qt-qml-app/main.py, samples/qt-qml-app/main.qml
~~Not ready for review, just want to check if it works.~~
Ready for review :) Leaving the comment spam to illustrate the development process of the size check 🤣 I am aware these comments may get on our nerves at some point, but we can make them conditional when they do get annoying. I think there might be value in running this check on every commit anyways...
=> Bug 1676145 - Setup CI 

.circleci/config.yml, bin/build-size-check.sh
I also try to make the percentage prettier by limiting it to two decimal cases.
=> Bug 1681516 - Fix percentage calc for size check CI

.gitignore, tests/utils/webext/index.ts, tests/utils/webext/sample/package-lock.json, tests/utils/webext/sample/package.json
This basically uses web-ext to package the sample addon and tweaks the test to pick up the right name.
=> Fix running integration tests on Windows

src/dispatcher.ts, src/glean.ts
This should fix the test log spam.
=> Uninitialize the dispatcher on testResetGlean

src/dispatcher.ts, tests/dispatcher.spec.ts
Also...
- Add a cool little test about launching tasks inside other tasks
- Strongly advise against blocking on the dispatcher queue outside
of tests through code coments and docstrings.
=>  Bug 1690536 - Make all dispatcher tasks into launched commands

CHANGELOG.md, glean/package-lock.json
=> Bumped version to 0.1.0

glean/src/core/glean.ts
This only changes the indentation. I think this was mistakenly changed, since it's only part of the file.
=> Fix the indentation in glean.ts from 3 to 2 spaces

docs/adding_a_new_metric_type.md
[Rendered](https://github.com/brizental/glean.js/blob/1690995-doc-new-metric/docs/adding_a_new_metric_type.md)
=> Bug 1690995 - Document how to add a new metric type

glean/src/core/glean.ts, glean/src/core/metrics/database.ts, glean/src/core/pings/database.ts, glean/src/platform/index.ts, glean/tests/core/metrics/database.spec.ts, glean/tests/core/pings/database.spec.ts
This is the first part, taking care of the circular dependencies for the database. I decided to split the changes, because the next ones will be a bit more involved, and I'm not sure it's worth rabbit holing in it right now.
=> Bug 1698874 - Sever the circular dependencies in the database

.github/dependabot.yml
=> No bug - Update dependabot.yml for new folder structure

glean/package.json
=> Fix path for creating commonjs package.json

glean/src/core/dispatcher.ts, glean/tests/core/glean.spec.ts
Also found a small bug in `dispatcher.testUninitialze`.
=> No bug - Add a test to verify Glean's behaviour against specific async + sync calls scenario

glean/src/cli.ts, glean/src/core/glean.ts, glean/tests/core/metrics/boolean.spec.ts, glean/tests/core/metrics/counter.spec.ts, glean/tests/core/metrics/datetime.spec.ts, glean/tests/core/metrics/string.spec.ts, glean/tests/core/metrics/uuid.spec.ts, glean/tests/core/pings/index.spec.ts, glean/tests/platform/uploader.spec.ts
I habitually correct spelling errors as I glance through code, these just happen to cross my path.
=> Some spelling errors corrected

samples/web-extension/javascript/src/index.js, samples/web-extension/javascript/webpack.config.js
Good thing we will have CI checks for these soon! :D
=> No bug - Port javascirpt webext sample to ES6

glean/.eslintrc, glean/src/core/metrics/events_database.ts, glean/src/core/metrics/types/event.ts, glean/src/core/metrics/types/labeled.ts, glean/src/core/metrics/types/labeled_utils.ts, glean/src/core/metrics/types/uuid.ts, glean/src/core/pings/database.ts, glean/src/core/pings/index.ts, glean/src/core/pings/maker.ts, glean/tests/core/metrics/counter.spec.ts, glean/tests/core/metrics/event.spec.ts, glean/tests/core/metrics/events_database.spec.ts, glean/tests/core/metrics/labeled.spec.ts, glean/tests/core/metrics/string.spec.ts, glean/tests/core/metrics/uuid.spec.ts, glean/tests/core/pings/database.spec.ts, glean/tests/core/pings/maker.spec.ts, glean/tests/core/upload/index.spec.ts, glean/tests/platform/storage.spec.ts
I'm not sure why we didn't have this :)
=> Enable the no trailing spaces eslint rule

CHANGELOG.md, glean/src/index/qt.ts, glean/src/platform/qt/index.ts, samples/qt-qml-app/README.md
This additionally reshapes the README to use python virtual environments and fixes a small typo.
=> Expose the missing metrics on the QT platform

.circleci/config.yml, samples/web-extension/typescript/package-lock.json, samples/web-extension/typescript/package.json, samples/web-extension/typescript/tests/unit/index.test.ts
Creating a new pull request after the generated folder was created.
=> Bug 1702425 - Add tests to Typescript sample and CI job to run them

CHANGELOG.md, glean/src/core/glean.ts, glean/src/core/pings/ping_type.ts, glean/tests/integration/schema/schema.spec.ts
This addresses the bug discovered by the Rally team ( thanks @hamilton !) in mozilla-rally/rally-core-addon#641.
=> Fix broken `deletion-request`

.github/PULL_REQUEST_TEMPLATE.md, glean/src/core/metrics/metric.ts
Apparently just adding this file is enough for it to show up as a PR template once it is merged.
=> Bug 1686673 - Add PR checklist template

.circleci/config.yml, README.md, glean/package.json, glean/src/index/qt.js, samples/web-app-static/index.html
=> Replace all occurances of Javascript with JavaScript

glean/tests/unit/platform/storage.spec.ts, glean/tests/unit/platform/utils/webext/index.ts
Initializing it inside the test suite, made the test fail silently
unless run in an isolated command.
=> Bug 1717845 - Initialize Firefox WebDriver globally

glean/src/metrics.yaml
=> No bug - Add missing telemetry_sdk_build metric to metrics.yaml

glean/package-lock.json
Something happened with the dependabot PR's rebasing that caused this issue. Notice that `main` lint job has failed.
=> No bug - Update package-lock.json

CHANGELOG.md, glean/src/core/constants.ts, glean/src/core/context.ts, glean/src/core/glean.ts, glean/src/core/metrics/database.ts, glean/src/core/metrics/events_database.ts, glean/src/core/metrics/events_database/index.ts, glean/src/core/metrics/events_database/recorded_event.ts, glean/src/core/metrics/types/event.ts, glean/src/core/pings/maker.ts, glean/src/core/utils.ts, glean/src/metrics.yaml, glean/tests/unit/core/metrics/database.spec.ts, glean/tests/unit/core/metrics/events_database.spec.ts
=> Bug 1716724 - Implement new logic to sort events from different application runs

glean/tests/unit/core/metrics/events_database.spec.ts
This seems to have fix it. I say it "seems" to have fixed it because this is how I tested:
- Ran the tests 10x with the original code. Got test failures 4 out of those 10 times.
- Applied the fixes.
- Ran the tests 10x with the new code. Got no failures.
=> Bug 1724382 - Fix off-by-one intermittent error in EventsDatabase tests

glean/package-lock.json
=> Fix the outdated package lock file

.circleci/config.yml, glean/src/cli.ts, samples/node/README.md, samples/node/index.js, samples/node/main.js, samples/node/main.test.js, samples/node/metrics.yaml, samples/node/package-lock.json, samples/node/package.json, samples/node/pings.yaml, samples/qt-qml-app/requirements.txt, samples/web-extension/javascript/README.md, samples/web-extension/typescript/README.md
~This is a draft until https://github.com/mozilla/glean_parser/pull/390 makes it into a release and `glean_parser` is updated here.~ https://github.com/mozilla/glean_parser/releases/tag/v4.1.0
=> Bug 1728809 - Implement a simple Node.js sample app

.circleci/config.yml, CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts, samples/qt-qml-app/main.qml
=> Bumped version to 0.21.0

.circleci/config.yml, glean/package-lock.json, glean/package.json
The issues were fixed by running `npm run audit --force`. 
Nice suggestion, thanks @birdsarah !
=> Bug 1733634 - Add audit step to CI and fix dependency issues

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/platform/browser/uploader.ts, glean/src/platform/browser/web/index.ts, glean/src/platform/browser/web/storage.ts, glean/tests/unit/platform/storage.spec.ts
- https://bugzilla.mozilla.org/show_bug.cgi?id=1736352
=> Bug 1726726 - Implement a Store for the web platform

CHANGELOG.md, glean/src/core/config.ts, glean/tests/unit/core/config.spec.ts
=> Bug 1730496 - Don't allow http server endpoints outside of testing mode'

CHANGELOG.md, glean/src/core/upload/index.ts
- https://github.com/mozilla/glean/pull/1880
=> Bug 1742371 - Update rate limit to allow 40pings/minute

glean/src/core/context.ts, glean/src/core/glean.ts, glean/src/core/metrics/database.ts, glean/src/core/metrics/events_database/index.ts, glean/src/core/pings/database.ts, glean/src/core/upload/index.ts, glean/tests/unit/core/glean.spec.ts, glean/tests/unit/core/metrics/database.spec.ts, glean/tests/unit/core/metrics/events_database.spec.ts, glean/tests/unit/core/pings/database.spec.ts, glean/tests/unit/core/upload/index.spec.ts
=> Bug 1742063 - Use standalone uploader in uploader tests

glean/src/core/upload/manager.ts, glean/tests/unit/core/upload/manager.spec.ts
Follow up with minor bug fix from #988 
- Changelog from #988 is enough, the bug that I fix here has never been released.
- Actually found this bug while writing the docs for [Bug 1687288](https://bugzilla.mozilla.org/show_bug.cgi?id=1687288).
=> No bug - Do not increment rate limiter if there are no pending pings

.circleci/config.yml, CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts, samples/qt/src/App/App.qml, samples/qt/src/Tests/tst_maintests.qml
=> Release v0.29.0

glean/src/cli.ts, samples/qt/requirements.txt
Sorry @brizental , the last version had a silly bug.
=> Bumped glean_parser version to 5.0.1

.dictionary, CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/cli.ts
...And with as many arguments as the users wants to.
=> Bug 1699392 - Enable running the glean command offline

samples/browser/webext/manifest.json
- https://github.com/mozilla/glean/pull/1966
=> No bug - Drop host permissions from webext sample

CHANGELOG.md, glean/src/core/glean.ts, glean/src/core/testing/utils.ts, glean/src/index/base.ts, glean/tests/unit/core/glean.spec.ts, glean/tests/utils.ts
=> Bug 1749293 - Apply debug features before sending pings at init

.circleci/config.yml
From brizental@mozilla.com to data sre managed.
New context was created in circleci 'data-sre-gleanjs'
=> [DSRE-584] Migrate ownership on circleci for github and npm bot

.circleci/config.yml, CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts, samples/qt/src/App/App.qml, samples/qt/src/Tests/tst_maintests.qml
=> Bumped version to 1.1.0

ARCHITECTURE.md, automation/README.md, docs/guides/adding_a_new_metric_type.md, docs/guides/update_glean_parser.md, glean/src/cli.ts
I checked the code and some readMe files, code comments, etc had some typos and grammar mistakes so I fixed them
=> Fixed some grammers and typos in comments & readMe files

CHANGELOG.md, glean/src/cli.ts, samples/qt/requirements.txt
=> Bug 1832231 - Bumped glean_parser version to 7.2.1

automation/size/report.js
=> Unconditionally print size report

glean/package-lock.json, glean/package.json
=> Revert "Bump geckodriver from 3.2.0 to 4.0.4 in /glean"

automation/compat/index.js, automation/compat/tests/utils.js
=> Fix typos to correct browserstack tests

.dictionary, CHANGELOG.md
=> Add missing changelogs for LocalStorage updates

.circleci/config.yml, .dictionary, CHANGELOG.md, docs/reference/sizes.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts, samples/qt/README.md, samples/qt/src/App/App.qml, samples/qt/src/Tests/tst_maintests.qml
=> Bumped version to 2.0.0

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 2.0.1

CHANGELOG.md, docs/reference/sizes.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 2.0.2

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 2.0.3

CHANGELOG.md, docs/reference/sizes.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 2.0.4

.vscode/launch.json
Instead of hardcoding the path to one test file, the proposed change runs the currently opened and active file in the debugger.
=> Improve the individual file VSCode debug config

CHANGELOG.md, glean/src/cli.ts
=> Bump the glean parser to 10.0.3

CHANGELOG.md, docs/reference/sizes.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 3.0.0-pre.1

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Release v3.0.0

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 4.0.0-pre.0

CHANGELOG.md
=> Add the missing glean sync entry to changelog

CHANGELOG.md
=> Add the missing sendBeacon changelog entry

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 4.0.0-pre.1

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Bumped version to 4.0.0-pre.2

.dictionary, CHANGELOG.md, docs/reference/metrics.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Release v4.0.0 pre.3

.dictionary, glean/src/core/config.ts, glean/src/core/glean.ts, glean/src/core/pings/maker.ts, glean/src/metrics.yaml, glean/tests/unit/core/pings/maker.spec.ts
=> Bug1850323 - Add experimentation_id to Glean.js

CHANGELOG.md
=> Add sendBeacon fallback uploader to changelog

automation/compat/index.js
=> Bug 1862955 - Remove optional chaining from browserstack tests

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Release v4.1.0 pre.0

samples/browser/web/src/index.html, samples/browser/web/src/index.js
Hooks up automatic click instrumentation on the web sample project.
=> Bug 1886443 - automatic click events in web sample project

CHANGELOG.md, glean/package-lock.json, glean/package.json, glean/src/core/constants.ts
=> Release v5.0.0 pre.0

CHANGELOG.md
Add a few missing changelogs before I cut the `5.0.1` release.
=> missing changelogs for #1919 & #1921

README.md
I've paid my Glean.js dues, I think its time my name gets added to the team.
=> add brosa to the glean team

.dictionary
=> add brosa to .dictionary

glean/src/cli.ts
=> Bumped glean_parser version to 14.5

ARCHITECTURE.md
=> Architecture doc updates

.circleci/config.yml
3.9 is really old and the image is based on Ubuntu 20.04, which is EoL for a while now.
=> Use a newer Python
