mozilla/glean.js

- .eslintrc
- bin/build-size-check.sh
- package-lock.json
- package.json
- samples/web-extension/README.md
- src/index.ts
- src/storage/index.ts
- src/storage/persistent/webext.ts
- src/storage/utils.ts
- src/storage/weak.ts
- tsconfig.json
- webpack.config.qt.js
- webpack.config.shared.js
- webpack.config.webext.js
This is a split off of #7, containing only the storage implementation for web extensions. This doesnt contain tests as I am still figuring out last issue with testing direcly on browsers. This might mean that there are bugs on this implementation, but since I have done manual testing, no big changes should come on the tests PR and the overall approach will still be the same.
> Bug 1679375 - Implement a Storage that uses the web ext storage API

- .eslintrc
- package.json
- src/database.ts
- src/metrics/index.ts
- src/storage/persistent/index.ts
- src/storage/utils.ts
- tests/database.spec.ts
As was described in the proposal, the database module will differ from the glean-core database module.
While it will serve as an abstraction layer over the underlying storage, it will also be the interface to retrive the ping / metric payload data from the storage. This is a bit easier for Glean.js, because the data is saved already in the format that is expected by the ping schema.
I will leave comments on the code about some doubts that lingered after I was finished with this implementation.
> Bug 1679375 - Implement the base of the metrics database module

- .eslintrc
- package.json
- src/database.ts
- src/metrics/boolean.ts
- src/metrics/counter.ts
- src/metrics/payload.ts
- src/metrics/string.ts
- src/storage/index.ts
- src/utils.ts
- tests/database.spec.ts
- tests/metrics/counter.spec.ts
- tests/utils/webext/index.ts
The second commit (008bce4) is a bonus. I am not sure that is a good pattern, but it does centralize payload validation instead of doing it in a bunch of different places and in different ways, and I think that at least is good. Please let me know what you think :)
> Bug 1679380 - Implement the counter metric type

- src/constants.ts
- src/glean.ts
- src/metrics/database.ts
- src/metrics/types/boolean.ts
- src/metrics/types/counter.ts
- src/metrics/types/datetime.ts
- src/metrics/types/string.ts
- src/metrics/types/uuid.ts
- src/metrics/utils.ts
- src/pings/database.ts
- src/pings/index.ts
- src/pings/maker.ts
- src/utils.ts
- tests/metrics/boolean.spec.ts
- tests/metrics/counter.spec.ts
- tests/metrics/database.spec.ts
- tests/metrics/datetime.spec.ts
- tests/metrics/string.spec.ts
- tests/metrics/uuid.spec.ts
- tests/pings/database.spec.ts
- tests/pings/index.spec.ts
- tests/pings/maker.spec.ts
- tests/utils.spec.ts
- tsconfig.json
This PR turned out to be bigger than I expected, there are many things interconnected. I tried to make it as lean as possible, but I can also break if off into two PRs, one for the pings database and another that relies on that for ping type and ping maker. Please let me know if you would like me to do that.
In Glean.js we can't just save pings in files, so I created the concept of a pings database, which is an abstraction over the underlying storage just like the metrics database.
> Bug 1677445 - Implement PingType and ping maker

- bin/qt-js-check.sh
- package.json
- samples/qt-qml-app/main.qml
- src/config.ts
- src/glean.ts
- src/index.ts
- src/metrics/index.ts
- src/metrics/types/uuid.ts
- src/pings/index.ts
- src/pings/maker.ts
- src/storage/persistent/webext.ts
- src/storage/utils.ts
- src/storage/weak.ts
- src/upload/index.ts
- src/upload/uploader/browser.ts
- src/upload/uploader/index.ts
- src/utils.ts
- tests/glean.spec.ts
- tests/pings/maker.spec.ts
- tests/upload/uploader.spec.ts
- tests/utils.spec.ts
- webpack.config.shared.js
- webpack.config.webext.js
Now that we can acutally measure it, for reference:
- The webext build is 46K.
- The qt build is 44K.
> Bug 1687644 - Implement the external API for consumers

- samples/web-extension/generatedMetrics.js
- samples/web-extension/generatedPings.js
- samples/web-extension/index.js
- samples/web-extension/manifest.json
- samples/web-extension/package-lock.json
- samples/web-extension/package.json
- samples/web-extension/popup.html
- samples/web-extension/popup.js
- samples/web-extension/webpack.config.js
- src/glean.ts
- src/storage/persistent/webext.ts
- src/upload/uploader/browser.ts
This is a continuation of #27.
Glean.js works :) See the pings sent from the sample: https://glean-debug-view-dev-237806.firebaseapp.com/pings/glean.js-test. Chrome and Firefox, but you'll need to take my word for it, that information is not in the metrics yet.
I did encounter some bugs upon testing in Chrome, which were not major so I fixed them. I think it will be important to have a kinda real testing playground for the next task I'll tackle which is [Bug 1687491](https://bugzilla.mozilla.org/show_bug.cgi?id=1687491).
It is also clear that in the future we will need to have automated testing in both browsers, the errors I fixed in the storage I only found because I tested in Chrome.
> Bug 1687644 - Use the new external API on the web ext sample

- src/dispatcher.ts
- src/glean.ts
- tests/dispatcher.spec.ts
This is part 1. 
Other PRs will come for actually using this dispatcher on the external APIs.
> Bug 1687491 - Implement a dispatcher and add an instance to the Glean singleton

- .eslintrc
- package.json
- src/glean.ts
- src/index.ts
- src/metrics/events_database.ts
- src/metrics/index.ts
- src/metrics/types/event.ts
- src/metrics/utils.ts
- src/pings/database.ts
- src/pings/maker.ts
- src/utils.ts
- tests/metrics/database.spec.ts
- tests/metrics/event.spec.ts
- tests/metrics/events_database.spec.ts
See the individual commit messages descriptions for easier review.
This exclusively adds the metric type, it doesn't take care of adding the 'events' ping.
> Bug 1688902 - Create the events metric type

- samples/qt-qml-app/generatedMetrics.js
- samples/qt-qml-app/generatedPings.js
- samples/qt-qml-app/main.qml
- samples/web-extension/index.js
- src/config.ts
- src/glean.ts
- src/index.ts
- src/pings/index.ts
- src/pings/maker.ts
- tests/glean.spec.ts
Well this was kinda neat so I am going to add videos to the description.
https://user-images.githubusercontent.com/25176023/107064134-78602e00-67db-11eb-8fff-1c4af9843410.mov
https://user-images.githubusercontent.com/25176023/107064143-7b5b1e80-67db-11eb-9d24-973ab9990dc8.mov
Not only is it cool, but it helps us validate further the dispatcher PR as a side effect, since log pings relies on it. We know now that it works even in Qt.
Note: This is blocked until the dispatcher PR is merged.
> Bug 1691068 - Implement log pings

- src/constants.ts
- src/glean.ts
- src/internal_pings.ts
- src/pings/index.ts
- src/upload/index.ts
- tests/glean.spec.ts
The approach here is a bit different than the approach in glean-core.
I ported all the tests I found from the core and the android bindings and they all passed. 
**What's different?**
I skipped having a different storage for deletion requests and instead treat them as any other ping. I also added a special case, so that the deletion-request ping is sent even if upload is disabled.
> Bug 1686685 -  Implement the deletion request ping

- .circleci/config.yml
- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
- samples/web-extension/README.md
- samples/web-extension/index.js
- samples/web-extension/package-lock.json
- samples/web-extension/package.json
This is on top of #72. As such, it is blocked until that PR is merged (or not merged).
Dry run logs for reference:
```
> @mozilla/glean@0.1.0 prepare .
> npm run build
> @mozilla/glean@0.1.0 build /Users/beatrizmachado/Documents/work/glean.js/glean
> webpack --config webpack.config.js --mode production
asset qt.js 54.7 KiB [emitted] [minimized] (name: main)
orphan modules 18.7 KiB [orphan] 14 modules
runtime modules 670 bytes 3 modules
modules by path ./src/ 87.9 KiB
modules by path ./src/core/ 84 KiB 24 modules
modules by path ./src/platform/ 2.39 KiB
./src/platform/qt/index.ts 408 bytes [built] [code generated]
./src/platform/test/index.ts 1010 bytes [built] [code generated]
./src/platform/test/storage.ts 1.01 KiB [built] [code generated]
./src/index.ts 1.42 KiB [built] [code generated] …
```
> Bug 1686678 - Prepare Glean.js for publishing

- CHANGELOG.md
- glean/package.json
If the README.md is not in the glean package folder, it will not be included in the final package and as a consequence will not show up on the package npm page.
> Bug 1693297 - Copy README.md on prepublish

- .circleci/config.yml
What made the publishing job not run on the last release were the requires, we were requiting jobs that don't run on tags. 
Anyways I removed those requires, in the docs we already tell people to wait for CI to go green before tagging.
I also updated the regex to match exactly [what we do on the Glean SDK repository](https://github.com/mozilla/glean/blob/main/.circleci/config.yml#L13-L18). The initial regex was not wrong, but I thought it would probably be best to just make it exactly tthe same.
> Bug 1693298 - Remove requires and update regex from ci release script

- CHANGELOG.md
- glean/package.json
- glean/src/core/metrics/index.ts
- glean/tsconfig/base.json
- glean/tsconfig/webext/browser.json
- glean/tsconfig/webext/cjs.json
- glean/tsconfig/webext/esm.json
- samples/web-extension/typescript/package-lock.json
- samples/web-extension/typescript/package.json
- samples/web-extension/typescript/src/index.ts
- samples/web-extension/typescript/tsconfig.json
- samples/web-extension/typescript/webpack.config.js
Currently when attempting to import the @mozilla/glean package in the Bergamot extension, we get the following error: 
```bash
Cannot find module '@mozilla/glean/webext' or its corresponding type declarations.
```
I am mostly sure that the problem is with our types definitions. If you look at [this thread ](https://github.com/microsoft/TypeScript/issues/33079), you'll notice that it is not ironed out exactly how [`exports`](https://nodejs.org/api/packages.html#packages_subpath_exports) and type declarations play together.
I have used the `typesVersions` workaround since the change to use `exports`, because I am basing myself off of how [`jose`](https://github.com/panva/jose/blob/main/package.json) does thigs.
I seem to be using it incorrectly. In this branch I made some experiements. …
> Fix errors when importing Glean.js in Typescript environments

- glean/src/core/config.ts
- glean/src/core/events/index.ts
- glean/src/core/events/utils.ts
- glean/src/core/glean.ts
- glean/src/core/pings/database.ts
- glean/src/core/pings/maker.ts
- glean/src/plugins/index.ts
- glean/tests/core/events.spec.ts
- glean/tests/core/glean.spec.ts
- glean/tests/core/pings/maker.spec.ts
Different approach for #94 (and my preferred approach, 1) Less cleverness on the types 2) Less relying on the Glean singleton).
Based off of [this thread](https://github.com/mozilla/glean.js/pull/94#discussion_r586471152).
> [ALTERNATE] Bug 1689547 -  Create plugin / events infrastructure and define `afterPingCollection` event

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/constants.ts
- glean/src/core/glean.ts
- glean/src/core/pings/maker.ts
- glean/src/core/utils.ts
- glean/src/index/qt.ts
- glean/src/index/webext.ts
- glean/tests/core/config.spec.ts
- glean/tests/core/glean.spec.ts
- glean/tests/core/pings/database.spec.ts
- glean/tests/core/pings/maker.spec.ts
- glean/tests/core/utils.spec.ts
Left the API to "unset" the tags because I had already written the code before realizing glean-core doesn't support it. I can remove it, to wait for a response on [Bug 1697198](https://bugzilla.mozilla.org/show_bug.cgi?id=1697198),  but I'd rather not since it seems like a no brainer.
Also, I tested it in the sample webext and 🎉 https://debug-ping-preview.firebaseapp.com/pings/ts-webext-test
> Bug 1685718 - Add support for debug view and source tags setting 

- CHANGELOG.md
- glean/src/core/upload/index.ts
- glean/tests/core/upload/index.spec.ts
Example header sent from our web extension sample `Glean/0.4.0 (JS on Darwin)`.
> Bug 1697208 - Include a Glean User-Agent header in all pings

- CHANGELOG.md
- glean/.eslintrc
- glean/package-lock.json
- glean/package.json
- glean/src/core/events/index.ts
- glean/src/core/pings/maker.ts
- glean/src/plugins/encryption.ts
- glean/tests/core/glean.spec.ts
- glean/tests/core/metrics/boolean.spec.ts
- glean/tests/core/metrics/counter.spec.ts
- glean/tests/core/metrics/database.spec.ts
- glean/tests/core/metrics/datetime.spec.ts
- glean/tests/core/metrics/event.spec.ts
- glean/tests/core/metrics/events_database.spec.ts
- glean/tests/core/metrics/string.spec.ts
- glean/tests/core/metrics/uuid.spec.ts
- glean/tests/core/pings/database.spec.ts
- glean/tests/core/pings/index.spec.ts
- glean/tests/core/pings/maker.spec.ts
- glean/tests/core/upload/index.spec.ts
- glean/tests/plugins/encryption.spec.ts
- glean/tsconfig/webext/browser.json
- glean/tsconfig/webext/cjs.json
- glean/tsconfig/webext/esm.json
- glean/tsconfig/webext/types.json
Opening this as a draft to get feedback on the encryption implementation.
> Bug 1689547 - First attempt at providing a ping encryption plugin

- CHANGELOG.md
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/index.ts
- glean/src/core/metrics/types/labeled.ts
- glean/src/core/metrics/utils.ts
- glean/tests/core/metrics/labeled.spec.ts
This introduces the labelled metric types for string, boolean and counter types. The implementation closely follows what's in the Glean SDK, with no major deviation.
Note that this required adding a couple more functions to the database.
TODO:
> Add labeled metric types

- .gitignore
- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
- glean/src/cli.ts
- glean/tsconfig/cli.json
- samples/web-extension/javascript/README.md
- samples/web-extension/javascript/package.json
- samples/web-extension/typescript/README.md
- samples/web-extension/typescript/package.json
This exposes a "glean" command to be used as an interface for running the glean_parser by glean.js
consuming products. It takes care of setting up a virtual environment and making sure that the parser
and its dependencies are up to date.
How to test this:
- Add glean.js to a project via `npm link`
- Run `npx glean ....` and check the generated output.
For rally, I had this output:
```
dexter@DX-WORKHORSE:/mnt/d/Mozilla/rally/core-addon$ npx glean translate metrics.yaml pings.yaml -f javascript -o public/generated
Checking for a Glean virtual environment at /mnt/d/Mozilla/rally/core-addon/.venv
Using Glean virtual environment at /mnt/d/Mozilla/rally/core-addon/.venv
```
TODO:
> Expose a "glean" command

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/src/core/upload/uploader.ts
- glean/src/platform/test/index.ts
- glean/src/platform/test/storage.ts
- glean/src/platform/webext/uploader.ts
- glean/tests/core/upload/index.spec.ts
- glean/tests/platform/uploader.spec.ts
This PR ended up being bigger than anticipated, sorry. It does:
- Make `Uploader` a proper interface rather than an abstract class.
- Inject instances of the uploader to `PingsDatabase` rather than having it directly call `Glean.platform.uploader`.
- Fixes `WeakStore` to behave like other stores.
- Adds `httpClient` as a configuration option (the naming is consistent with the other bindings).
See the individual commit messages for more information.
> Bug 1687287 - Support setting a custom uploader

- glean/src/core/events/index.ts
- glean/src/core/glean.ts
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/events_database.ts
- glean/src/core/metrics/index.ts
- glean/src/core/metrics/metric.ts
- glean/src/core/metrics/metrics_interface.ts
- glean/src/core/metrics/types/boolean.ts
- glean/src/core/metrics/types/counter.ts
- glean/src/core/metrics/types/datetime.ts
- glean/src/core/metrics/types/string.ts
- glean/src/core/metrics/types/uuid.ts
- glean/src/core/metrics/utils.ts
- glean/src/core/pings/database.ts
- glean/src/core/pings/maker.ts
- glean/src/core/pings/ping_payload.ts
- glean/src/plugins/encryption.ts
- glean/tests/core/metrics/events_database.spec.ts
This PR brings down the circular dependencies detected by `npm run lint:circular-deps` from 34 to 20.
These are the low hanging fruits. I'll follow up with other work next.
> Bug 1701578 (Part 1) - Remove some circular dependencies

- glean/src/core/glean.ts
- glean/src/core/pings/database.ts
- glean/src/core/upload/index.ts
- glean/tests/core/pings/database.spec.ts
- glean/tests/core/upload/index.spec.ts
This removes one more circular dependency, but it's quite a bit of work. We're now at 19!
I've got a few more PRs lined up.
> Bug 1701578 - Remove a circular dependency in the upload module

- glean/src/core/metrics/database.ts
- glean/src/core/metrics/index.ts
- glean/src/core/metrics/types/labeled.ts
- glean/src/core/metrics/types/labeled_utils.ts
> Bug 1701578 - Remove circular dependency from labeled.ts

- .circleci/config.yml
- glean/src/core/context.ts
- glean/src/core/dispatcher.ts
- glean/src/core/glean.ts
- glean/src/core/metrics/types/boolean.ts
- glean/src/core/metrics/types/counter.ts
- glean/src/core/metrics/types/datetime.ts
- glean/src/core/metrics/types/event.ts
- glean/src/core/metrics/types/string.ts
- glean/src/core/metrics/types/uuid.ts
- glean/src/core/pings/index.ts
- glean/src/core/pings/maker.ts
- glean/tests/core/glean.spec.ts
- glean/tests/core/metrics/boolean.spec.ts
- glean/tests/core/metrics/counter.spec.ts
- glean/tests/core/metrics/database.spec.ts
- glean/tests/core/metrics/datetime.spec.ts
- glean/tests/core/metrics/labeled.spec.ts
- glean/tests/core/metrics/string.spec.ts
- glean/tests/core/metrics/uuid.spec.ts
- glean/tests/core/pings/index.spec.ts
- glean/tests/core/pings/maker.spec.ts
- glean/tests/core/upload/index.spec.ts
- glean/tests/plugins/encryption.spec.ts
As discussed with @brizental , this introduces a new shared state object called `Context` and uses that in the metric types, instead of referring to the Glean object (creating circular dependencies).
It additionally makes the `Dispatcher` a singleton.
Finally, it enabled the circular dependencies checker on CI.
> Bug 1701578 - Remove the final circular dependencies!

- glean/src/cli.ts
Instead of printing the whole exception, this exclusively prints stdout and stderr.
In case of error, here's what gets printed:
```
npx glean glinter src/*.yaml
Checking for a Glean virtual environment at /mnt/c/Mozilla/glean.js/samples/web-extension/javascript/.venv
Using Glean virtual environment at /mnt/c/Mozilla/glean.js/samples/web-extension/javascript/.venv
ERROR running glean_parser v2.5.0
==============================================================================
/mnt/c/Mozilla/glean.js/samples/web-extension/javascript/src/metrics.yaml:
```
sample: webext_started!
```
'webext_started!' is not valid under any of the given schemas
'webext_started!' does not match '^[a-z_][a-z0-9_]*$'
```
> Bug 1699394 - Improve the error reporting of the Glean cli tool

- CHANGELOG.md
- glean/package.json
Not sure how we didn't pick this up before, but ok.
> Bug 1706024 - Fix path to ping entry point in package.json

- CHANGELOG.md
- glean/src/cli.ts
- glean/src/core/metrics/utils.ts
- glean/tests/core/metrics/labeled.spec.ts
Without this fix products using these types silently fail ping submission with the following error:
```
Error executing task: Error: Unable to create metric of unknown type labeled_boolean
at createMetric (file:///mnt/d/Mozilla/rally/core-addon/node_modules/@mozilla/glean/dist/webext/core/metrics/utils.js:17:15)
at createMetricsPayload (file:///mnt/d/Mozilla/rally/core-addon/node_modules/@mozilla/glean/dist/webext/core/metrics/database.js:30:28)
at MetricsDatabase.getPingMetrics (file:///mnt/d/Mozilla/rally/core-addon/node_modules/@mozilla/glean/dist/webext/core/metrics/database.js:153:20)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async collectPing (file:///mnt/d/Mozilla/rally/core-addon/node_modules/@mozilla/glean/dist/webext/core/pings/maker.js:98:25)
at …
```
> Fix labeled booleans and string

- .circleci/config.yml
- CHANGELOG.md
I copied the way the Glean SDK does it and also how it names the final file.  I tested this locally and it worked, I added a Qt asset to the 0.9.2 with the loca test, see https://github.com/mozilla/glean.js/releases/tag/v0.9.2. 
(self reminder: For this to work I need to add a `GITHUB_TOKEN` env var to CircleCI).
> Bug 1706103 - Add step to relase Qt build in Publish CI script

- CHANGELOG.md
- glean/src/core/context.ts
- glean/src/core/glean.ts
- glean/tests/core/context.spec.ts
This guarantees the dispatcher is always available even before the Glean initialization. We need this because our APIs can be used before initialization, to perform fast recording of metrics.
> Bug 1705720 - Ensure the dispatcher is always available

- glean/src/core/dispatcher.ts
- glean/tests/core/dispatcher.spec.ts
This PR removes the mechanism based on timeouts and observers to wait on test tasks in the dispatcher. It instead defines a new task type, TestTask, and passes a resolver function when its created.
> Remove the observer mechanism to wait for test tasks

- CHANGELOG.md
- glean/src/core/pings/ping_type.ts
- glean/tests/core/pings/index.spec.ts
- glean/tests/core/pings/ping_type.spec.ts
This implements the pings testing API, as discussed and designed in the related bug.
> Bug 1701889 - Implement the ping testing api

- CONTRIBUTING.md
- docs/getting_started.md
This PR fixes bug 1707601 on BugZilla, and hopefully this would help JavaScript newbies (like me!)
However, there may be more things to be added to the `getting_started` doc.
Any suggestion is appreciated!
> Bug 1707601 - Add the doc for instructions on how to getting started (#)

- CHANGELOG.md
- glean/src/core/pings/maker.ts
I think the original logic is wrong, in that the message `Storage for ${ping.name} empty. Ping will still be sent.` will be logged if `eventsData` is defined.
https://github.com/mozilla/glean.js/blob/0557f318a4637b471850313a8006f46a32b6a1fa/glean/src/core/pings/maker.ts#L198-L203
> Bug 1708366: Ensure only empty pings triggers logging of "empty ping" message

- CHANGELOG.md
- glean/src/core/platform_info.ts
- glean/src/platform/qt/index.ts
- glean/src/platform/qt/platform_info.ts
- glean/tests/core/glean.spec.ts
- glean/tests/plugins/encryption.spec.ts
- glean/tsconfig/qt.json
- glean/types/Qt/index.d.ts
This uses the global `Qt` object to get the OS name and the locale. Unfortunately, os version and architecture are not available.
I manually tested that this works using the Glean.js Qt sample app. I get the following output:
```
D:\Mozilla\glean.js\samples\qt-qml-app>python main.py
qml: Initialized Glean succesfully.
qml: Adding to the `button_clicked` metric.
qml: Attempted to delete an entry from an invalid index. Ignoring.
qml: {
"metrics": {
"datetime": {
"sample.app_started": "2021-05-06T16:17:26.529+02:00"
},
"counter": {
"sample.button_clicked": 1
}
},
"ping_info": {
"seq": 0,
"start_time": "2021-05-06T16:17+02:00",
"end_time": "2021-05-06T16:17+02:00"
},
"client_info": {
"telemetry_sdk_build": "0.11.0",
"client_id": "06cbc5b3-2c1b-4cc5-bdaf-85ba62a4afca",
"first_run_date": …
```
> Bug 1706102 - Collect Qt platform information

- .circleci/config.yml
The PR aims to tackle bug 1681484; 
Right now, `package-lock.json` is intentionally modified to see whether the newly added CI check fails as expected.
> Bug 1681484: Add the consistency check between package.json and package-lock.json

- bin/update-glean-parser-version.sh
- docs/update_glean_parser.md
This is all mostly copied over from https://github.com/mozilla/glean/blob/main/bin/update-glean-parser-version.sh and https://mozilla.github.io/glean/dev/upgrading-glean-parser.html
> Bug 1706043 - Add script and docs for updating glean_parser version

- .circleci/config.yml
- CHANGELOG.md
- bin/prepare-qml-module.sh
- bin/prepare-release.sh
- glean/.eslintignore
- glean/package.json
- glean/qt.entry.js
- glean/src/cli.ts
- glean/src/index/qt.js
- glean/src/index/qt.ts
- glean/src/index/webext.ts
- glean/webpack.config.qt.js
- samples/qt-qml-app/README.md
- samples/qt-qml-app/main.py
- samples/qt-qml-app/main.qml
- samples/qt-qml-app/requirements.txt
Opening as a draft as this depends on https://github.com/mozilla/glean_parser/pull/342
I have tested manually of course, but we will be sure once CI turns out green after updating glean_parser 👀 
Just remembered that I still need to:
> Bug 1707896 - Make the Qt package a QML module

- CHANGELOG.md
- glean/.eslintignore
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/events_database.ts
- glean/src/core/storage/utils.ts
Thought this was an actual bug. Glad it wasn't really :)
> Bug 1707581 - Check if there are ping data before attempting to delete it

- CHANGELOG.md
- glean/src/cli.ts
- glean/src/core/config.ts
- glean/src/core/dispatcher.ts
- glean/src/core/error/index.ts
- glean/src/core/events/index.ts
- glean/src/core/events/utils.ts
- glean/src/core/glean.ts
- glean/src/core/internal_metrics.ts
- glean/src/core/log.ts
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/events_database.ts
- glean/src/core/metrics/metric.ts
- glean/src/core/pings/database.ts
- glean/src/core/pings/maker.ts
- glean/src/core/pings/ping_type.ts
- glean/src/core/storage/utils.ts
- glean/src/core/upload/index.ts
- glean/src/core/utils.ts
- glean/src/platform/test/storage.ts
- glean/src/platform/webext/storage.ts
- glean/src/platform/webext/uploader.ts
- glean/tests/unit/core/pings/maker.spec.ts
This allows to easily add functionality to turn debug logs off. Filed a bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1715312
We should also audit the levels of these messages, some messages are internal error but are in the Error level. They should really be debug, or trace... Anyways, that can be done as part of the but I created above.
> Bug 1712285 - Tag all log messages

- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
- glean/src/core/upload/index.ts
- glean/src/core/upload/uploader.ts
- glean/src/platform/qt/fflate.stub.js
- glean/src/platform/test/index.ts
- glean/src/platform/webext/uploader.ts
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/plugins/encryption.spec.ts
- glean/tests/utils.ts
- glean/webpack.config.qt.js
Should I file a bug to document that pings are gzipped? I looked and that is not mentioned on the Glean book. That could be important for folks using custom uploaders for testing, but that could also be behaviour we want to disencourage... Even if we don't disencourage it, we might want to expose the [WaitableHttpClient](https://github.com/mozilla/glean.js/blob/main/glean/tests/integration/schema/schema.spec.ts#L46-L81) in the future. Then people still don't need to worry about gzipping.
- When changes to the …
> Bug 1712080 - Gzip ping paylod before upload

- CHANGELOG.md
- glean/src/core/metrics/types/event.ts
- glean/src/metrics.yaml
> [no bug] Record the events timestamp before dispatching

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- glean/src/index/qt.ts
- glean/src/index/webext.ts
- samples/web-extension/javascript/package.json
- samples/web-extension/javascript/tests/unit/index.test.js
- samples/web-extension/javascript/webpack.config.js
- samples/web-extension/typescript/package-lock.json
- samples/web-extension/typescript/package.json
- samples/web-extension/typescript/tests/unit/index.test.ts
- samples/web-extension/typescript/tsconfig.json
- samples/web-extension/typescript/webpack.config.js
Documentation PR: https://github.com/mozilla/glean/pull/1705
> Bug 1714365 - Expose ErrorType enum

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/tests/unit/core/upload/index.spec.ts
Fun fact: [we basically never reach this limit with glean-core](https://sql.telemetry.mozilla.org/queries/80821/source).
> Bug 1712922 - Implement ping body size limit

- CHANGELOG.md
- benchmarks/size/webext/max.js
- docs/adding_a_new_metric_type.md
- glean/src/cli.ts
- glean/src/core/metrics/types/timespan.ts
- glean/src/core/metrics/types/url.ts
- glean/src/core/metrics/utils.ts
- glean/src/index/qt.ts
- glean/tests/integration/schema/metrics.yaml
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/core/metrics/url.spec.ts
- samples/qt-qml-app/pings.yaml
- samples/qt-qml-app/requirements.txt
- samples/web-extension/javascript/src/pings.yaml
- samples/web-extension/typescript/src/pings.yaml
- https://github.com/mozilla/glean/pull/1715
...Also missing:
- https://github.com/mozilla/glean_parser/pull/361
- https://github.com/mozilla/glean_parser/releases/tag/v3.7.0
- https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/689
Both these changes block this PR, before them the integration tests will not pass.
> Bug 1719315 - Implement the URL metric type

- glean/src/metrics.yaml
From the probe-scraper:
```
docker-compose run app python -m probe_scraper.check_repositoriesCreating probe-scraper_app_run ... done
Summary of validation errors:
1 repositories had problems
Errors found in glean-js:
230:81: line too long (84 > 80 characters) (line-length)
``` …
> Fix linting issue in metrics.yaml

- CHANGELOG.md
- glean/src/core/dispatcher.ts
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/src/index/qt.js
- glean/src/index/qt.ts
- glean/src/index/webext.ts
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/core/dispatcher.spec.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/metrics/labeled.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/core/pings/ping_type.spec.ts
- glean/tests/unit/core/upload/index.spec.ts
- glean/tests/unit/plugins/encryption.spec.ts
- glean/tests/utils.ts
The lack of this API causes a bug in Rally. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1698934#c33
I have confirmed that this fixes the issue and makes the test over on https://github.com/mozilla-rally/rally-core-addon/pull/678 pass.
- https://github.com/mozilla/glean/pull/1722
> Bug 1707891 - Implement shutdown API

- CHANGELOG.md
- glean/package-lock.json
- glean/src/core/dispatcher.ts
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/tests/unit/core/dispatcher.spec.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/upload/index.spec.ts
- glean/tests/utils.ts
- https://github.com/mozilla/glean/pull/1722
> Bug 1707891 - Do not clear deletion-request pings when clearing pings queue

- CHANGELOG.md
- glean/.eslintrc
- glean/src/core/dispatcher.ts
- glean/src/core/glean.ts
- glean/src/core/pings/database.ts
- glean/src/core/upload/index.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/pings/database.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/core/upload/index.spec.ts
- This behaviour is already documented on the Glean book: https://mozilla.github.io/glean/book/user/pings/index.html?highlight=10MB#limitations
> Bug 1712921 - Implement ping storage size limit

- glean/src/metrics.yaml
The Glinter yaml check otherwise fails, e.g. in probe-scraper.
---
See e.g. https://app.circleci.com/pipelines/github/mozilla/probe-scraper/663/workflows/b1b2f155-9e0f-4934-98ab-d17cbf417975/jobs/1094
> Wrap description line before 80-char limit

- CHANGELOG.md
- glean/package-lock.json
- glean/src/cli.ts
- glean/src/core/metrics/events_database/index.ts
- glean/src/core/metrics/events_database/recorded_event.ts
- glean/src/core/metrics/types/event.ts
- glean/tests/integration/schema/metrics.yaml
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/core/metrics/event.spec.ts
- glean/tests/unit/core/metrics/events_database.spec.ts
- samples/qt-qml-app/requirements.txt
- This behaviour [is already documented on the Glean book](https://mozilla.github.io/glean/book/reference/metrics/event.html), although looking at the docs I think they might benefit from having examples for quantity and boolean extra types too. I'll follow-up with a PR to the Glean book updating it.
~**Opening as a draft: I'll make the necessary changes to glean_parser and then update glean_parser in this PR before it is ready.**~
> Bug 1693487 - Accept booleans and numbers as event extras

- CHANGELOG.md
- glean/src/core/upload/index.ts
- glean/src/core/upload/rate_limiter.ts
- glean/tests/unit/core/upload/index.spec.ts
- glean/tests/unit/core/upload/rate_limiter.spec.ts
This actually fixes a bug: there was no code path to re-start the PingUploader dispatcher once it was stopped due to max recoverable error being hit. None of our consumers have updated yet,s o if I make a release after this is merged we should be fine.
- https://github.com/mozilla/glean/pull/1758
> Bug 1712920 - Implement rate limiting in ping upload

- CHANGELOG.md
- glean/package-lock.json
- glean/src/platform/qt/storage.ts
- glean/webpack.config.qt.js
- I'll file a follow up to document how to use the development version. It requires changing the `glean.js` file inside the Qt library folder, which is... kinda horrible, but at this point, better than nothing.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1727352
> Bug 1726769 - Include development version in Qt/QML build

- CHANGELOG.md
- benchmarks/size/webext/max.js
- glean/src/cli.ts
- glean/src/core/metrics/types/text.ts
- glean/src/core/metrics/utils.ts
- glean/src/index/qt.ts
- glean/tests/integration/schema/metrics.yaml
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/core/metrics/text.spec.ts
- samples/qt-qml-app/requirements.txt
The new text metric type is really just a long string,
but only allowed under specific circumstances.
---
Draft while I fix outstanding things:
> Bug 1726327 - Implement the new text metric type

- CHANGELOG.md
- glean/src/core/pings/database.ts
- glean/src/core/storage/index.ts
- glean/src/platform/qt/storage.ts
- glean/src/platform/test/storage.ts
- glean/src/platform/webext/storage.ts
- glean/tests/unit/core/metrics/database.spec.ts
- glean/tests/unit/core/metrics/events_database.spec.ts
- glean/tests/unit/core/metrics/labeled.spec.ts
- glean/tests/unit/core/pings/database.spec.ts
- glean/tests/unit/core/pings/ping_type.spec.ts
- glean/tests/unit/platform/storage.spec.ts
> Bug 1727349 - Drop _getWholeStore API from Store impls

- .circleci/config.yml
- benchmarks/README.md
- benchmarks/package.json
- benchmarks/run.sh
Instead of switching back and forth between branches this uses an
additional worktree.
This guarantees that the benchmark runs fully against code in the main
branch first, then fully against code in the current checkout.
This requires that the report code in the latest checkout needs to be
able to consume the report from the `main` branch,
so be careful when changing its format.
---
I decided to do this in an external script.
That seems to be easier than to cram this into individual npm scripts.
~~Also note: this will only start working properly AFTER this PR has been merged and can't be tested on this PR.~~
> Bug 1727269 - Run the size benchmark against a full main checkout

- .github/auto_assign.yml
As discussed in today's meeting.
> Add chutten and mdboom to the Glean.js reviewers rotation

- glean/src/core/dispatcher.ts
- glean/src/core/upload/index.ts
- glean/tests/unit/core/dispatcher.spec.ts
- glean/tests/unit/core/upload/index.spec.ts
I also found another bug on the rate limit implementaion while working on this bug, which is fixed in 5be95ad.
Detailed descriptions on the commit messages explain the changes made.
- I think CHANGELOG changes are unnecessary here. This is part of rate limiting implementation, which is already there.
> Bug 1727318 - Dispatcher can't be stopped while it's being shutdown

- CHANGELOG.md
- glean/src/core/context.ts
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/tests/unit/core/context.spec.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/metrics/labeled.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/core/pings/ping_type.spec.ts
After tests, I confirmed none of the sample apps were recording the `glean.restarted` event when Glean was initialized :/ That was the case, because we were calling `eventsDatabase.initialize` before setting `Context.uploadEnabled`. That meant `Context.uploadEnabled` was `undefined` upon events database initialization and `undefined` being a falsy value, `.shouldRecord()` was returning `false`, which resulted in the `glean.restarted` and `execution_counter` metrics not being recorded.
In 8324569 I fix that and in 4cb6118 I add a test to ensure that if this behaviour ever changes we will see test failures.
The commits in between these two commits are there to make sure the test _does_ fail if the behaviour is changed. I actually found a bug in the way we were reseting Glean in tests. We …
> Bug 1728128 - Ensure events database is initialized at a time when metrics can be recorded

- CHANGELOG.md
- glean/src/core/platform_info.ts
- glean/src/platform/node/index.ts
- glean/src/platform/node/platform_info.ts
This is what the ping looks like when sent from Node.js in my computer.
```json
(Glean.core.Pings.Maker) {
"ping_info": {
"seq": 0,
"start_time": "2021-09-03T12:08+02:00",
"end_time": "2021-09-03T12:08+02:00"
},
"client_info": {
"telemetry_sdk_build": "0.19.0",
"client_id": "7f7aacd9-7d4d-4ca5-bc69-2ab9f2705e08",
"first_run_date": "2021-09-03+02:00",
"os": "Darwin",
"os_version": "20.6.0",
"architecture": "x64",
"locale": "en-US",
"app_build": "Unknown",
"app_display_version": "Unknown"
}
}
```
- Not really sure how to write a test for this, but I guess in this manual testing is enough.
> Bug 1728808 - Implement a PlatformInfo module that works in Node.js

- .github/auto_assign.yml
All dependabot PRs start with the word "Bump". 
There are way too many dependabot PRs basically everyday, it will get annoying soon if auto assign keeps asking people for review on them.
> No bug - Skip auto assign for dependabot PRs

- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
- glean/src/platform/node/index.ts
- glean/src/platform/node/uploader.ts
- glean/src/platform/qt/uploader.ts
- glean/tests/unit/platform/node/uploader.spec.ts
It works: https://debug-ping-preview.firebaseapp.com/pings/node-js
- Documentation on the whole Node.js stuff will come on https://bugzilla.mozilla.org/show_bug.cgi?id=1728983
> Bug 1728810 - Implement an uploader for the Node.js platform

- glean/src/core/metrics/types/url.ts
- glean/tests/unit/core/metrics/url.spec.ts
- [] **Changelog**: This PR includes a changelog entry to `CHANGELOG.md` or an explanation of why it does not need one
> Bug 1729629: Remove URI encoding for the url metric type

- glean/package-lock.json
- glean/package.json
- glean/tsconfig/qt.json
- glean/webpack.config.qt.js
This group of changes was yanked from #744 . 
I took them out of there to make that PR a bit smaller, but also because this group is not immediatelly related to the fix over there. I just happened to find these issues while working on that investigation.
> No bug - Change Qt compilation config to make final lib smaller and target correct specification

- CHANGELOG.md
- glean/src/core/dispatcher.ts
- glean/src/core/glean.ts
- glean/src/core/internal_metrics.ts
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/index.ts
- glean/src/core/metrics/types/labeled.ts
- glean/src/core/pings/maker.ts
- glean/src/core/upload/rate_limiter.ts
- glean/tests/unit/core/metrics/events_database.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/plugins/encryption.spec.ts
- samples/qt-qml-app/main.qml
I just took the relevant commits from #744
> Bug 172777 - Apply workarounds to known Qt JS issues

- glean/package.json
On tagging 0.21.0 the `publish to npm` step failed in CI due to `npm build:webext` not being available.
This commit https://github.com/mozilla/glean.js/commit/d73a93f777a3e7525be778e8ee9baae72f237abd#diff-509bb202baa8df0d26bbf11ae91491e2b3a9ae00a1b7528aa215ad5941c9909cL79 removed `build:webext` but did not remove the call to it in the `prePublishOnly` script.
Also, worth noting that refs to `build:webext` are in `benchmarks/package.json` but I have not fixed those in this PR as I don't know the best replacement.
> Fix publish step

- .circleci/config.yml
- glean/package.json
This probably got broken during one of dependabots updates, so now I added a CI job for us to know when dependabot breaks the build commands.
> Bug 1734730 - Fix docs build and add build CI job

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/utils.ts
- This is a bugfix, changelog entry is enough.
> Bug 1738118 - Make sure Context.uploadEnabled always has a value

- CHANGELOG.md
- glean/src/index/node.ts
- glean/src/index/web.ts
- glean/src/index/webext.ts
Left Qt out of this on purpose, seems to be a bit more involved to
expose these over there and no one is currently asking for it.
- I filed a follow up bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1741133. Using custom uploader is really under documented so the bug is more generic.
> Bug 1740772 - Expose Uploader, UploadResult and UploadResultStatus

- CHANGELOG.md
- glean/src/cli.ts
- https://bugzilla.mozilla.org/show_bug.cgi?id=1741829
> Bug 1741581 - Attempt to get virtualenv name from environment

- glean/tests/unit/plugins/encryption.spec.ts
> Bug 1702251 - Don't rely on Glean internals on plugins tests

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/tests/unit/core/glean.spec.ts
The metrics public APIs already do type checking. The pings `submit` API also checks if reason is valid. Other Glean singletons APIs also do validation of arguments.
The only API missing was uploadEnabled really. 
> Bug 1738208 - Add runtime type check to args passed to setUploadEnabled API

- CHANGELOG.md
- glean/src/core/upload/index.ts
- glean/tests/unit/core/upload/index.spec.ts
The previous behaviour would enqueue a Stop command on the
uploader dispatcher everytime a ping submit happening while
the uploader was throttled or stopped due to other limitations.
That resulted in the dispatcher being immediatelly stopped once
it was resumed due to the throttling window being over, because
the first command it would see would be a stop command.
That could result in long lasting periods of time when the uploader
was just stopped and not processing ping requests.
> Bug 1741898 - Don't enqueue multiple stop command on uploader dispatcher

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/glean.ts
- glean/tests/unit/core/config.spec.ts
- glean/tests/unit/core/context.spec.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/plugins/encryption.spec.ts
- samples/browser/webext/src/index.ts
The reason for this change is to be consistent with the other SDKs. None of them allow to pass debug options on init.
Best to make this change now that we don't have that many users.
- This was never documented specifically because we did not want people to use it.
> Bug 1712914 - Remove debug options from configuration object

- CHANGELOG.md
- glean/src/core/upload/index.ts
- glean/tests/unit/core/upload/index.spec.ts
This is a bug in the implementation and a surprising one at that.
That is a comment right above the line I just fixed saying "we want
an unrecoverable failure here..." which is followed by returning
a recoverable failure.
> No bug - Return unrecoverable result in case unable to build ping request

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/src/core/upload/index.ts
- glean/src/core/upload/manager.ts
- glean/src/core/upload/policy.ts
- glean/src/core/upload/rate_limiter.ts
- glean/src/core/upload/task.ts
- glean/src/core/upload/uploader.ts
- glean/src/core/upload/worker.ts
- glean/tests/unit/core/glean.spec.ts
- glean/tests/unit/core/metrics/labeled.spec.ts
- glean/tests/unit/core/pings/maker.spec.ts
- glean/tests/unit/core/pings/ping_type.spec.ts
- glean/tests/unit/core/upload/index.spec.ts
- glean/tests/unit/core/upload/manager.spec.ts
- glean/tests/unit/core/upload/rate_limiter.spec.ts
- glean/tests/unit/core/upload/worker.spec.ts
- glean/tests/utils.ts
With the previous design it was hard and hacky to enforce the rate limit defaults at the correct time.
The new design (or old, depends on how you look at it) allows to do that easily. 
It also has the following added benefits 1) logic is better encapsulated in different structures 2) the design is almost exactly the same as the one in glean-core, so transfer of knowledge and ensurace of standardized functionality is easier to do 3) it doesn't have an internal dispatcher instance 4) it's just easier to reason about it, IMO.
Note: I suggest reviewing this PR commit by commit. I did my best to isolate changes, but this is a big change and there is no going around that.
- The gist of this …
> Bug 1742093 - Refactor upload management logic to be exactly like in glean-core

- glean/src/core/context.ts
- glean/src/core/glean.ts
- glean/src/core/log.ts
This was creating an annoying log spam in tests because
Glean would always attempt to access the platform before
it was set on the first time calling testResetGlean.
> No bug - Don't attempt to access platform before it was set in Context 

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/tests/unit/core/glean.spec.ts
Checking inside the task had no meaning, because that would guarantee
the check to be executed _after_ the initialize task. That is the case,
because the initialize task is _always_ the first task to be executed by
the dispatcher regardless of any other previously dispatched tasks.
> No bug - Check if Glean is initialized before dispatching toggle upload task

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/tests/unit/core/glean.spec.ts
- Docstring has been updated. Don't think there are any other places to update.
> Bug 1742450 - Make shutdown a no-op in case Glean is not initialized

- CHANGELOG.md
- glean/src/core/upload/manager.ts
- glean/src/core/upload/worker.ts
- glean/src/platform/browser/web/index.ts
- glean/src/platform/browser/webext/index.ts
- glean/src/platform/index.ts
- glean/src/platform/node/index.ts
- glean/src/platform/qt/index.ts
- glean/src/platform/test/index.ts
- glean/tests/unit/core/upload/worker.spec.ts
- glean/tests/utils.ts
> Bug 1727076 - Have PingUploadWorker sleep in case it gets a Wait task

- CHANGELOG.md
- glean/src/core/dispatcher.ts
- glean/src/platform/qt/storage.ts
Updated logs when unable to access the database now look like this:
```
qml: (Glean.platform.qt.Storage.pingLifetimeMetrics) Error executing LocalStorage query: CREATE TABLE IF NOT EXISTS pingLifetimeMetrics(key VARCHAR(255), value VARCHAR(255));.
Error: Driver not loaded Driver not loaded
QSqlQuery::prepare: database not open
qml: (Glean.platform.qt.Storage.appLifetimeMetrics) Error executing LocalStorage query: CREATE TABLE IF NOT EXISTS appLifetimeMetrics(key VARCHAR(255), value VARCHAR(255));.
Error: Driver not loaded Driver not loaded
QSqlQuery::prepare: database not open
qml: (Glean.platform.qt.Storage.events) Error executing LocalStorage query: CREATE TABLE IF NOT EXISTS events(key VARCHAR(255), value VARCHAR(255));.
Error: Driver not loaded Driver not loaded
QSqlQuery::prepare: …
```
> Bug 1740448 - Provide informative error message when unable to access DB in QML

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/tests/integration/schema/schema.spec.ts
This is how deletion-request pings were looking like before the fix.
```
(Glean.core.Pings.Maker) {
"ping_info": {
"seq": 0,
"start_time": "2022-01-10T14:36+01:00",
"end_time": "2022-01-10T14:36+01:00"
},
"client_info": {
"telemetry_sdk_build": "0.29.0",
"client_id": "da8d1774-2704-4828-ac4c-e2949f55d887",
"first_run_date": "2022-01-10+01:00"
}
}
```
> Bug 1749301 - Do not clear app lifetime metrics if sending deletion-request ping on init

- CHANGELOG.md
- glean/package-lock.json
- glean/src/core/context.ts
- glean/src/core/glean.ts
- glean/src/core/metrics/database.ts
- glean/src/core/metrics/index.ts
- glean/src/core/metrics/types/boolean.ts
- glean/src/core/metrics/types/counter.ts
- glean/src/core/metrics/types/datetime.ts
- glean/src/core/metrics/types/quantity.ts
- glean/src/core/metrics/types/rate.ts
- glean/src/core/metrics/types/string.ts
- glean/src/core/metrics/types/string_list.ts
- glean/src/core/metrics/types/text.ts
- glean/src/core/metrics/types/timespan.ts
- glean/src/core/metrics/types/url.ts
- glean/src/core/metrics/types/uuid.ts
- glean/src/core/metrics/utils.ts
- glean/tests/unit/core/metrics/database.spec.ts
Sending this in as a draft because I would like to get some feedback on the approach before moving on. More details on the commit messages, but this is a part of attempting to make the Glean.js bundle size smaller.
The changes do not make as a drastic a dent in the size of the bundle as #1051, however these changes are guards against making the bundle much larger in the future. As we add more metric types the bundle wouldn't get bigger.
My main concern is outlined in aaa1ce0. 
> I am not entirely sure about this change, because it means that if a
> given metric is in the database, but was not added to the metric map
> (think if a metric is removed from the code, but has not been collected
> in a ping once the new code lands) it will be read as invalid by Glean.
This could cause some …
> Bug 1746375 - Dynamically add metric constructors to metric map 

- CHANGELOG.md
- glean/src/core/upload/worker.ts
- glean/tests/unit/core/upload/worker.spec.ts
- https://github.com/mozilla/glean/pull/1911
> Bug 1742613 - Remove deprecated headers from Glean pings

- CHANGELOG.md
- glean/src/core/utils.ts
- glean/tests/unit/core/metrics/timespan.spec.ts
We were previously extracting the TIME_ORIGIN from Date.now()
in case performance.now was not available in the environment.
That could create negative timestamps, because Date.now is not
guaranteed to be monotonically increasing. (Yeah... it is
contradictiory to have a function called getMonotonicNow, but not
guarantee monotonically increasing timestamps for some platforms.
At least there is a TODO comment to address the incoherence at
some point).
Subtracting the TIME_ORIGIN was essentially pointless and I don't really
know why that was the case before. That function is used by the Timestamp
metric type and for event timestamps which are both about elapsed time,
so the absoulte timestamp should not matter.
EXTRA: Address stray TODO comment on TimespanMetricType test suite.
- Inside the …
> Bug 1751402 - Guarantee getMonotonicNow doesn't return a negative value

- CHANGELOG.md
- glean/src/cli.ts
- samples/qt/requirements.txt
> [Bug 1753194] - Bumped glean_parser version to 5.0.0

- CHANGELOG.md
- glean/src/platform/browser/webext/storage.ts
**###** Pull Request checklist ###
> Bug 1723130 - Provide comprehensive error message when permissions are incorrect for webexts

- CHANGELOG.md
- glean/src/cli.ts
This changeset minorly refactors how Glean detects virtual environments, in order to support virtualenvs that aren't in the project root. 
This was a problem for projects that wanted to use Glean, but had a virtual environment created separately and located elsewhere (eg in `$HOME/.virtualenvs/` or `$HOME/.pyenv/3.X.X/some/venv/path/` -- Glean would fail to detect them and would make a `.venv` directory in the project root.
The changes mean it's now possible to run Glean with a virtual environment created by `virtualenv` or `pyenv-virtualenv` without causing a Glean-specific `.venv` dir to be created.
**With a virtualenv that already exists, elsewhere on the filesystem (eg one made …
> 1219: Allow use of standalone virtual environments (eg, one created by virtualenv)

- CHANGELOG.md
- docs/guides/release.md
- glean/src/cli.ts
Yes, users could potentially use "glean --version"
but that would install glean_parser. This command allows
to retrieve the glean_parser version without installing it.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1742642#c4
Example: 
```
% ./node_modules/.bin/glean --glean-parser-version
5.0.1
```
- https://bugzilla.mozilla.org/show_bug.cgi?id=1741829
> Bug 1742642 - Add command to retrieve glean parser version on the Glean CLI

- CHANGELOG.md
- glean/src/core/metrics/events_database/recorded_event.ts
- glean/src/core/pings/database.ts
- glean/tests/unit/core/pings/database.spec.ts
This was causing a bug in the following situation:
1. User submits a ping that contains custom headers
2. Restarts the app, the app scans the pending pings directory
3. Ping is thrown away because validation function only accepts pings with 2 to 3 properties and since v0.19.0 the internal pings have 3 to 4 properties due to the addition of the `collectionDate` property.
> Bug 1760556 - Update internal ping validation function to account for collectionDate e prop

- CHANGELOG.md
- glean/src/platform/node/uploader.ts
- glean/tests/unit/platform/node/uploader.spec.ts
This additionally adds the related test coverage.
> [No Bug] Fix gzipped ping upload for Node.

- automation/compat/tests/utils.js
Due to security restrictions in Safari, BrowserStack uses a host named [bs-local.com](https://www.browserstack.com/question/39574) instead of localhost for the test content. We should account for that in the webpack-dev-server, otherwise it will fail reporting "Invalid Header"
Webpack-dev-server [docs](https://webpack.js.org/configuration/dev-server/#devserverallowedhosts).
- Documentation should …
> Allow connections other than localhost for Safari tests

- CHANGELOG.md
- bin/prepare-release.sh
- samples/qt/README.md
- ~~Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API~~
- ~~When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository~~
- ~~Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code changes~~
I was able to test this locally by using this portion of the `prepare-release` script and running it from the `/samples/qt` directory.
```bash
set -eo pipefail
DOIT=y
SED="sed"
WORKSPACE_ROOT="."
NEW_VERSION=1.1.0 # change this …
```
> Bug 1786272 - Qt sample project updates

- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
The maintainers of the `ts-node` package added this fix to their repo in version 10.8.0 to deal with the short-circuit ESM errors. I was able to run all tests from the `glean` directory as well as confirm that all the samples projects are still working as expected.
https://github.com/TypeStrong/ts-node/pull/1715
- ~~Documentation should be added to [The Glean Book](https://mozilla.github.io/glean/book/index.html) when making changes to Glean's user facing API~~
- ~~When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) repository~~
- ~~Documentation should be added to [the Glean.js developer …
> Bug 1785127 - Upgrade ts-node package to 10.8.0 to fix ESM issues

- .dictionary
CI spellcheck step is failing because of a few words. This, along with #1457, is the reason that all the dependabot PRs show failing checks.
Example of a failing CI job - https://app.circleci.com/pipelines/github/mozilla/glean.js/4025/workflows/b56fc69a-474f-4f54-b079-1868785156cf/jobs/18266/steps
From the top level of the Glean.js repo, run `bin/spellcheck.sh list `, you should see no misspelled words.
- When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) …
> Add words to dictionary to fix spellcheck CI step

- CHANGELOG.md
- samples/browser/webext/package-lock.json
- samples/browser/webext/package.json
I discovered that the `webext` tests were broken with newer versions of node. This is the same issue that we saw with the main glean package tests. I did not realize at first that this sample project also had its own tests and the same issues as the glean tests. The same fix that we did for glean proper can be applied here.
Notes on the other sample projects tests
- **`web`** - This project does not have tests, so there is nothing to fix.
- **`node`** - This project uses `mocha` directly for testing, it does not do any of the experimental ESM stuff like `glean` & `webext`
- **`qt`** - The tests for this project has issues, but they are not related to the `ts-node` versions. I am logging a bug for those to be worked on separately.
1. Run `npm run test` from inside of the …
> Fix ts-node version issue with webext sample project

- automation/README.md
Added
- `npm install` step, its required
- `npm run link:glean` step, not required since it will happen
automatically, but running it manually causes less permissions issues
- note about permissions issue that can happen and how to fix
We don't need a changelog or documentation update since this is just a small README fix. …
> Update `automation` README

- .github/dependabot.yml
Now that we are getting more up-to-date, we likely aren't going to need weekly checks. We can move this to monthly and on the first of the month, we can review and merge the PRs. It is currently on weekly, which is causing it to just open too many PRs.
This does not need an entry in the changelog or require a documentation update. …
> Bug 1790785 - Update dependabot PR frequency

- CHANGELOG.md
- glean/src/cli.ts
On Windows, users were unable to use the `npm run glean` command because the way we passed the python script as a long, template literal broke the CLI. By moving that script to its own file, executing it, then deleting it, we are able to successfully run the command.
I tested this on Mac and Windows and I am now able to get my `pings` file generated when running `npm run glean`.
**This is a bug fix, it does not require documentation changes.**
- When changes to the Glean Book are necessary, link to the corresponding PR on the …
> Bug 1790035 - Write python script to temp file, execute, then delete

- CHANGELOG.md
- glean/src/core/metrics/types/url.ts
- glean/src/core/utils.ts
- glean/tests/unit/core/metrics/url.spec.ts
I updated the URL metric `URL_MAX_LENGTH` to be 8k rather than 2k.
I tested this in browser sample project by creating a string of length ~16000 chars and verifying in debug viewer that it was truncated to `8192` characters.
**Documentation**
`glean` PR to update metric & docs - https://github.com/mozilla/glean/pull/2199 …
> Bug 1790949 - bump url metric limit to 8k

- automation/package-lock.json
- automation/package.json
Reverts mozilla/glean.js#1527
`browser-compat-smoke-tests` are failing after merging this, we can revert to see if this fixes it
https://email.circleci.com/c/eJxFT0FuxCAMfA25EQVICDnksFW1PfTU9gGVF0zCFkJESLft60u0lSpZlmc8Y3lwZFK2ivNBqMqMSg6qcqPAZrBPzf769vyALFlM7vRS_ytV35O2WeOWwdfaJe2RepxAf9MlZmcdJvrJqNadla1Vmpo8fMlqHg0iDKoXHZMdXJgxTCkjrDA9M6C0qfw457xuRJwIP5e6H9eu1jEUOM2lhfjjvIcDeoSlvm5l5I3ggojznsO7hrCCmxYiHm8xfVgfb9SC82gIl4cgoHF7KGsMhf4jt7gnjYW8R9CQXVyqNKa4wXxJ-xJL5ukwHM_8At9fZY8
> Revert "Bump selenium-webdriver from 4.4.0 to 4.5.0 in /automation"

- CHANGELOG.md
- automation/size/utils.js
- glean/src/core/metrics/types/custom_distribution.ts
- glean/src/entry/qt.ts
- glean/src/histogram/exponential.ts
- glean/src/histogram/functional.ts
- glean/src/histogram/histogram.ts
- glean/src/histogram/linear.ts
- glean/tests/integration/schema/metrics.yaml
- glean/tests/integration/schema/schema.spec.ts
- glean/tests/unit/core/metrics/custom_distribution_exponential.spec.ts
- glean/tests/unit/core/metrics/custom_distribution_linear.spec.ts
Implements the Custom Distribution metric.
The documentation for the Glean book is updated in this PR - https://github.com/mozilla/glean/pull/2205
> Bug 1716951 - Implement the Custom Distribution Metric

- CHANGELOG.md
- glean/src/cli.ts
- glean/tests/integration/schema/schema.spec.ts
- samples/qt/requirements.txt
Updates the version of `glean_parser` that Glean.js uses. This is currently the latest version of `glean_parser` that has support added for the `rate` metric, specifically for Glean.js.
> Bug 1793777 - Update glean_parser to  v6.2.1

- automation/package-lock.json
- automation/package.json
Reverts mozilla/glean.js#1561
Looks like CircleCI builds started having issues after merging. I will look at what we need to do to upgrade next time this dependency tries to update.
> Revert "Bump selenium-webdriver from 4.4.0 to 4.6.0 in /automation"

- .dictionary
- CHANGELOG.md
- glean/src/core/internal_metrics/sync.ts
- glean/src/core/utils.ts
- glean/src/platform/browser/web/platform_info.ts
- glean/src/platform/browser/web/storage.ts
Adds additional checks to verify `window` and `localStorage` object exist before making any calls. This handles errors that are ONLY generated when compiling an SSR project. If you run an SSR project locally, the errors don't show because the browser has access to the `window` object.
This was tested by
- Creating a new nextjs project
- Integrating Glean.js
- Locally running `next dev`
- Building locally via `next build`
- Running the out directory on a simple web server via Python from my mac `python3 -m http.server`
- When changes to the …
> Bug 1845362 - SSR support for Glean.js

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/glean/sync.ts
- glean/src/core/internal_metrics/sync.ts
Conditionally migrate IDB data only if it already exists. If the project has never used an older version of Glean, then we want to avoid migration because of a potential race condition when submitting pings on first page load.
> Bug 1848200 - add migration flag to init

- docs/guides/update_glean_parser.md
- glean/src/cli.ts
I copied the script from https://github.com/mozilla/glean/blob/3c1c083238876dd6cc4e7577c66b73d309ab83d8/gradle-plugin/src/main/groovy/mozilla/telemetry/glean-gradle-plugin/GleanGradlePlugin.groovy#L61
This now uses `~=` for the glean-parser install, so we don't need to update glean.js for every glean_parser patch update.
> Update to glean-parser 8.1 and allow any patch version

- CHANGELOG.md
- glean/src/core/metrics/types/url.ts
Fixes #1753 
During the initial migration the URL `set` function didn't get a synchronous implementation.
[Recorded URL in the debug ping viewer](https://debug-ping-preview.firebaseapp.com/pings/glean-from-website/7a1ca7a9-eba8-4616-b8b6-3c27804e6834#L10)
- Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making …
> Bug 1849862 - sync URL set function

- CHANGELOG.md
- bin/python-env-vars-test.sh
- glean/package.json
- glean/src/cli.ts
Companion docs PR - https://github.com/mozilla/glean/pull/2620
changelog
- `GLEAN_PYTHON` env variable
- `GLEAN_PIP` env variable
> Bug 1852217 - allow setting python env variables

- CHANGELOG.md
- glean/src/core/glean/sync.ts
Allow setting debugging options from the browser console.
changelog
- support `window.Glean.setLogPings`
- support `window.Glean.setDebugViewTag`
- support `window.Glean.setSourceTags`
In the video the variable is `window.glean` ignore this, it is capitalized now. I just didn't rerecord the demo.
https://github.com/mozilla/glean.js/assets/24759139/d71f7dfb-62f7-45e2-a89b-534f6ac65894
- …
> Bug 1855392 - support window.Glean

- CHANGELOG.md
- automation/compat/tests/utils.js
- glean/src/core/glean/sync.ts
I tested this by pushing up a branch with the `dist` folder checked in and running this version directly inside of the `mdn` project. The `window is not defined` error goes away when wrapped in the `typeof window !== undefined` check.
> Bugs 1855792, 1855795 - window.Glean updates

- CHANGELOG.md
- glean/src/core/glean/sync.ts
- glean/src/core/utils.ts
Store the debug values set via `window.Glean` in `sessionStorage` which persists until the user closes the current tab.
I am not exactly sure what tests for this might look like. The only way to really write tests for this would be inside of BrowserStack, but to actually verify it works you need to see either console output or an entry in the debug ping viewer.
Doc updates - https://github.com/mozilla/glean/pull/2638
https://github.com/mozilla/glean.js/assets/24759139/b3ad5fbd-bb8b-40ec-a94d-b6c0411716ae
- When changes to the Glean Book are …
> Bug 1856730 - store debug values for session

- glean/src/core/glean/sync.ts
This PR also has some minor code changes
This error was reported by the MDN folks when upgrading to v2.0.2 & v2.0.4. I was able to test this by pushing up a branch with the dist folder checked in to my fork (https://github.com/rosahbruno/glean.js/tree/1858515-DIST-TEST) and install this using `gitpkg` in the MDN project and run the app locally.
`yarn run dev` with fixes on branch
`yarn run dev` with v2.0.4
- When changes to the Glean Book are necessary, link to the corresponding PR on the [`mozilla/glean`](https://github.com/mozilla/glean) …
> Bug 1858515 - Fix window is undefined error

- CHANGELOG.md
- glean/src/cli.ts
- glean/src/core/pings/common_ping_data.ts
- glean/src/core/pings/ping_type.ts
- samples/qt/requirements.txt
Besides bumping the `glean_parser` version, we made preciseTimestamps ping property optional to skip implementing this feature for now. This property can be made optional until this feature is actually implemented. This saves us having to change every place where we manually create a ping object, specifically in tests. …
> Bumped glean_parser version to 10.0.1

- .circleci/config.yml
- .dictionary
- docs/guides/release.md
The same mechanism was tested on my toy repo [here](https://github.com/Dexterp37/test_ci/blob/d0654884411fd41e900a6925df9aadcb0ffeba06/.circleci/config.yml#L45-L65). This is what I did for testing it there:
1. I merged my configuration changes
2. I cut 3 github releases, with the following tags: `real-random-v`, `v0.0.1`, `v0.0.2-pre.0`.
3. I checked that the triggered publish jobs acted as follows:
3a. For `real-random-v`, no workflow is triggered at all.
3b. For `v0.0.1`, the workflow for "release" is triggered.
3c. For `v0.0.2-pre.0` the workflow for "prerelease" is triggered.
These are the outputs I got:
Which seems to imply the conditions were working fine.
TODO:
- Documentation …
> Bug 1863916 - Add support for cutting 'prerelease' releases

- glean/src/platform/browser/uploader.ts
- glean/tests/unit/platform/browser/uploader.spec.ts
This changes the uploader code so that it doesn't wait for 10 seconds to check for timeouts.
> Make tests run a bit faster

- CHANGELOG.md
- glean/src/core/glean.ts
> Bug 1862270 - print messages to the console when debugging APIs are used

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/glean.ts
- glean/src/core/glean_metrics.ts
- glean/src/metrics.yaml
This PR implements the [first version](https://bugzilla.mozilla.org/show_bug.cgi?id=1867294#c24) to automatically collect click events on html elements:
1. It will record clicks to any [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) that have at least one of `data-glean-id`, `data-glean-type`, `data-glean-label` data attributes.
2. Additional context that is collected with this event (via [extra_keys](https://mozilla.github.io/glean/book/reference/metrics/event.html#extra-metric-parameters)):
1. `id`: A string indicating an identifier of the clicked element (takes its value from element's `data-glean-id` attribute value if present)
2. `type`: A string indicating the type of the clicked element (takes its value from element's `data-glean-type` attribute value if …
> Bug 1867294: Support for automatically collecting element click events (first version)

- CHANGELOG.md
- glean/src/core/metrics/types/event.ts
- glean/src/core/metrics/types/string.ts
- glean/src/core/metrics/types/string_list.ts
- glean/src/core/metrics/types/text.ts
- glean/src/core/utils.ts
- glean/tests/unit/core/metrics/event.spec.ts
- glean/tests/unit/core/metrics/string.spec.ts
- glean/tests/unit/core/metrics/string_list.spec.ts
- glean/tests/unit/core/metrics/text.spec.ts
> Bug 1868748 - truncate event extra strings to 500 bytes

- glean/src/core/config.ts
- glean/src/core/glean.ts
- glean/tests/unit/core/pings/maker.spec.ts
> Bug 1873061 - Add API to dynamically set experimentation id

- CHANGELOG.md
- automation/compat/index.html
- automation/compat/index.js
- automation/compat/tests/utils.js
- glean/src/core/config.ts
- glean/src/core/internal_metrics.ts
- glean/src/core/pings/maker.ts
- glean/src/core/pings/ping_payload.ts
- glean/src/core/sessions.ts
- glean/src/metrics.yaml
- glean/src/platform/browser/web/storage.ts
PR for updating Glean schema: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/795
> Bug 1862955 - Gleanjs session implementation

- automation/compat/index.js
This is a followup to #1850. The changes in that PR broke the browserstack tests. This updates our browserstack tests to rely on data from LocalStorage rather than trying to pull session IDs from log messages.
-  [x] **Documentation**: This PR includes documentation changes, an explanation of why it does not need that or a follow-up bug has been filed to do that work
- Documentation should be …
> Bug 1862955 - fix browserstack session tests

- glean/src/core/metrics/types/event.ts
Not sure how to best that other than manual, which I've done in the sample app.
We remove the glean_timestamp from testGetValue so consumers don't need to check for it.
> Bug 1886113 - Add wall-clock timestamps to all events

- CHANGELOG.md
- glean/src/core/glean_metrics.ts
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1885504
> [Bug 1885504] Improve automatic click events for nested elements

- glean/src/core/glean_metrics.ts
- glean/src/metrics.yaml
> Bug 1888430 - Add `page_id`  to Glean automatic events

- glean/src/core/pings/maker.ts
This fixes the way the experimentation id was getting added to pings that didn't have other metrics already in the payload.
> Bug 1893015 - Fix an issue where experimentation-id wasn't making it into certain pings

- CHANGELOG.md
- glean/src/cli.ts
- glean/src/core/pings/common_ping_data.ts
> Bumped glean_parser version to 14.0.1

- glean/src/core/pings/common_ping_data.ts
Add instructional comment and individual bugs to the list of unsupported `glean_parser` features.
> Bug 1894939: add bugs for not supported common_ping_data features

- CHANGELOG.md
- glean/src/core/config.ts
- glean/src/core/glean.ts
- glean/src/core/internal_metrics.ts
- glean/src/core/metrics/types/datetime.ts
The only documentation that we had of this was in the CHANGELOG, so there are no accompanying doc changes.
We are removing this migration code since it is no longer needed. The reason for this code was to help move `client_id`s and `first_run_date`s over from our previous storage solution from when Glean.js was asynchronous. Newer versions of Glean.js use `localStorage` which allows synchronous read/writes. Glean.js used to use `IndexedDB` which forced asynchronous read/writes.
Synchronous is necessary so that we can ensure read/writes execute before pages are unloaded. If we start to write to storage async and the page unloads, that process never finishes and we incur data loss.
The only product that used Glean.js in production that was migrating to our new storage solution was MDN. They …
> Bug 1894064: remove migration code

- documentation/astro.config.mjs
The new docs have been deployed, but since the site URL and base weren't set correctly, none of the routes were working as expected.
I updated the site and base to be
```ts
defineConfig({
site: 'https://mozilla.github.io',
base: '/glean.js',
...
});
```
- Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making …
> update docs site + base route

- .circleci/config.yml
This should fix the issue we are seeing where the docs have no styling or JS since GitHub pages is ignoring directories starting with an underscore
> add .nojekyll in docs-deploy step

- README.md
- docs/implementation/plugins-events.md
> Bug 1897203 - remove links to old docs

- CHANGELOG.md
- glean/package-lock.json
- glean/package.json
- glean/src/core/constants.ts
> Bumped version to 5.0.2

- documentation/src/content/docs/automatic_instrumentation/click_events.md
- documentation/src/content/docs/automatic_instrumentation/page_load_events.md
- documentation/src/content/docs/debugging/browser.md
- documentation/src/content/docs/getting_started/installation.md
- documentation/src/content/docs/getting_started/setup.md
- documentation/src/content/docs/playground.mdx
Add relative links so the base URLs are respected in markdown.
> Bug 1898681 - fix missing base url in md links

- documentation/src/content/docs/automatic_instrumentation/click_events.md
- documentation/src/content/docs/automatic_instrumentation/page_load_events.md
- documentation/src/content/docs/debugging/browser.md
- documentation/src/content/docs/getting_started/installation.md
- documentation/src/content/docs/getting_started/setup.md
- documentation/src/content/docs/playground.mdx
This needs a better solution, but for now manually adding the `/glean.js` to our local links should fix our issue.
Once this lands I will log a followup bug to address this better long-term.
> Bug 1898681 - hardcode base URL for links

- CHANGELOG.md
- automation/compat/tests/utils.js
- documentation/src/content/docs/debugging/browser.md
- glean/src/core/glean.ts
Accompanies work done in the DPV to allow for individual session debugging. Whenever the user calls `window.Glean.debugSession()` We will call `window.open()` with the appropriate DPV URL specifically displaying that session in the event stream.
- Documentation should be added to [the Glean.js developer documentation](https://github.com/mozilla/glean.js/tree/main/docs) when making internal code …
> Add window.Glean.debugSession() web API

- glean/package-lock.json
- glean/package.json
We no longer use typedoc, so we can remove it.
> remove unused typedoc package

- CHANGELOG.md
- glean/src/core/glean.ts
- I was not able to find any existing tests around sessionStorage or some kind of mock for the window object
- I'm not sure if we are going to tag a release right away.  I can update the changelog if that's the case.
- This PR doesn't change the API.  It prevents an uncaught error that could break some JS based webapps when Glean is in the dependency tree.
> Add try-catch around `window.sessionStorage` access

- CHANGELOG.md
- glean/src/core/glean.ts
- glean/src/core/internal_metrics.ts
- glean/src/core/sessions.ts
There are no changes to functionality for clients, so there are similarly no changes to tests or documentation. 
If we feel it would be imperative to add tests to cover these cases, please let me know!
> Bug 1943952 - update uses of sessionStorage and localStorage in core to be wrapped in a try/catch
